import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Shared building blocks for native PDF documents (true text, A4, paginated).
class PdfTheme {
  PdfTheme._();

  static const PdfColor primary = PdfColor.fromInt(0xFF0F4C81);
  static const PdfColor secondary = PdfColor.fromInt(0xFFEAF3FA);
  static const PdfColor border = PdfColor.fromInt(0xFFBBBBBB);

  static pw.Widget header({
    required String department,
    required String office,
    String? title,
    String? subtitle,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: <pw.Widget>[
        pw.Text(
          department.isEmpty ? 'Government Engineering Department' : department,
          style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold),
          textAlign: pw.TextAlign.center,
        ),
        if (office.isNotEmpty)
          pw.Text(office,
              style: const pw.TextStyle(fontSize: 11),
              textAlign: pw.TextAlign.center),
        pw.SizedBox(height: 6),
        pw.Divider(color: primary, thickness: 1.2),
        if (title != null) ...<pw.Widget>[
          pw.SizedBox(height: 4),
          pw.Text(title,
              style: pw.TextStyle(
                  fontSize: 13,
                  fontWeight: pw.FontWeight.bold,
                  color: primary)),
        ],
        if (subtitle != null)
          pw.Text(subtitle, style: const pw.TextStyle(fontSize: 10)),
      ],
    );
  }

  static pw.Widget footer(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 8),
      child: pw.Text(
        'Page ${context.pageNumber} of ${context.pagesCount}'
        '   |   Generated by GovScheme Pro',
        style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
      ),
    );
  }

  static pw.Widget labelValue(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 1.5),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: <pw.Widget>[
          pw.SizedBox(
            width: 150,
            child: pw.Text(label,
                style: pw.TextStyle(
                    fontSize: 9.5, fontWeight: pw.FontWeight.bold)),
          ),
          pw.Text(': ', style: const pw.TextStyle(fontSize: 9.5)),
          pw.Expanded(
              child: pw.Text(value, style: const pw.TextStyle(fontSize: 9.5))),
        ],
      ),
    );
  }

  static pw.Widget signatureBlock(String officer, String designation) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: <pw.Widget>[
        pw.SizedBox(height: 40),
        pw.Container(width: 180, child: pw.Divider(color: border)),
        pw.Text(officer.isEmpty ? 'Authorised Officer' : officer,
            style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
        if (designation.isNotEmpty)
          pw.Text(designation, style: const pw.TextStyle(fontSize: 9)),
      ],
    );
  }
}
